/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.squareshift.assignment;

import lombok.Generated;

@Generated
public class Library {
  public boolean someLibraryMethod() {
    return true;
  }
}
